MASTERDIR=	${.CURDIR}/../u-boot-master

PATCHFILES+=	1810050/raw \
		1810051/raw \
		1810052/raw \
		1810053/raw \
		1810054/raw

MODEL=		nanopi-r4s
BOARD_CONFIG=	nanopi-r4s-rk3399_defconfig
FAMILY=		rk3399

.include "${MASTERDIR}/Makefile"
